// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Native Medicine Garden",
  domain: "nativemedicinecannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "76 Gerrard St W, Toronto, ON M5G 1J5",
  streetAddress: "76 Gerrard St W",
  postalCode: "M5G 1J5",
  phone: "(437) 339-4466",
  phoneIntl: "+14373394466",
  neighborhood: "Downtown Toronto / Bay Street",
  nearbyAreas: ["Gerrard St W", "Bay St", "Yonge St", "Eaton Centre", "Dundas Station", "TTC", "College Street"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6586",
  longitude: "-79.3854",
  hours: ["Open 24 Hours"],
  seoTitle: "Native Medicine Garden | Weed Dispensary in Toronto",
  metaDescription: "Native Medicine Garden is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Gerrard St W", "Bay St", "Yonge St"],
  introVariant: "If you are searching for a reliable weed dispensary in Toronto, Native Medicine Garden at 76 Gerrard St W is your go-to destination. We serve adults 19+ with a vast selection of weed products including cannabis flower, pre-rolls, edibles, THC vapes, shatter, and CBD oils. Serving customers near Downtown Toronto / Bay Street and surrounding communities like Bay St, our cannabis store and weed shop is focused on quality and convenience.",
  neighborhoodDescription: "Located in the vibrant Downtown Toronto / Bay Street district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Paid parking is available in local garages and street meters",
  transitNote: "Steps from major TTC transit routes and college/dunder subway stations.",
  sectionTitle: "Serving Customers Near Downtown Toronto"
};
