export const gbpLocation = {
  storeName: "Native Medicine Garden",
  domain: "www.nativemedicinecannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "76 Gerrard St W, Toronto, ON M5G 1J5",
  streetAddress: "76 Gerrard St W",
  postalCode: "M5G 1J5",
  phone: "+1 (437) 374-4544",
  phoneIntl: "+14373744544",
  neighborhood: "Gerrard & Bay",
  nearbyAreas: ["Gerrard St W", "Bay St", "College–Bay", "College Park", "College Station", "Dundas Station", "University Avenue"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=76%20Gerrard%20St%20W%2C%20Toronto%2C%20ON%20M5G%201J5",
  mapEmbedUrl: "https://www.google.com/maps?q=76%20Gerrard%20St%20W%2C%20Toronto%2C%20ON%20M5G%201J5&output=embed",
  latitude: "43.6586",
  longitude: "-79.3854",
  hours: ["Open 24 Hours"],
  seoTitle: "Native Medicine Garden | Gerrard & Bay Walk-In",
  metaDescription: "Native Medicine Garden is a downtown walk-in at 76 Gerrard St W, Gerrard & Bay near College–Bay. Address, hours, and directions live on the homepage.",
  localLandmarks: ["Gerrard & Bay", "College Park", "College Station"],
  introVariant: "Native Medicine Garden is the walk-in cannabis shop at 76 Gerrard St W, on Gerrard Street West at Bay Street. This city URL is a supporting remnant — the homepage is the visit hub for address, hours, phone, and directions, and /visit covers how to reach Gerrard & Bay.",
  neighborhoodDescription: "The store is on Gerrard Street West at Bay Street, a short walk from College–Bay, College Station, and Dundas Station.",
  parkingNote: "Free evening street parking is available; check current street signs and nearby garage rules before parking",
  transitNote: "College and Dundas subway stations connect to nearby TTC routes",
  sectionTitle: "Gerrard & Bay downtown walk-in"
};
