export const gbpLocation = {
  storeName: "Native Medicine Garden",
  domain: "www.nativemedicinecannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "76 Gerrard St W, Toronto, ON M5G 1J5",
  streetAddress: "76 Gerrard St W",
  postalCode: "M5G 1J5",
  phone: "(437) 339-4466",
  phoneIntl: "+14373394466",
  neighborhood: "Downtown Toronto / Bay Street",
  nearbyAreas: ["Gerrard St W", "Bay St", "Yonge St", "Eaton Centre", "Dundas Station", "TTC", "College Street"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=76%20Gerrard%20St%20W%2C%20Toronto%2C%20ON%20M5G%201J5",
  mapEmbedUrl: "https://www.google.com/maps?q=76%20Gerrard%20St%20W%2C%20Toronto%2C%20ON%20M5G%201J5&output=embed",
  latitude: "43.6586",
  longitude: "-79.3854",
  hours: ["Open 24 Hours"],
  seoTitle: "Native Medicine Garden | Weed Dispensary in Toronto",
  metaDescription: "Visit Native Medicine Garden at 76 Gerrard St W in Toronto. Find store hours, directions, contact details, and menu-category links for adults 19+.",
  localLandmarks: ["Gerrard St W", "Bay St", "Yonge St"],
  introVariant: "Native Medicine Garden is located at 76 Gerrard St W in downtown Toronto near Bay Street. Adults 19+ can use this page to confirm the store address, phone number, hours, directions, and links to menu categories before visiting.",
  neighborhoodDescription: "The store is on Gerrard Street West near Bay Street, with Yonge Street and downtown Toronto destinations nearby.",
  parkingNote: "Check current street signs and nearby garage rules before parking",
  transitNote: "College and Dundas subway stations connect to nearby TTC routes",
  sectionTitle: "Serving Customers Near Downtown Toronto"
};
